version: 2
project_name: lsweb
builds:
- id: lsweb
  main: ./cmd/lsweb/main.go
  binary: lsweb
  goos:
  - linux
  - darwin
archives:
- id: lsweb
  format_overrides:
  - format: tar.gz
  files:
  - LICENSE
  - README.md
