name: lsweb
description: LS for websites
structure:
- dir: cmd
  children:
  - dir: lsweb
    children:
    - file: main.go
- dir: pkg
  children:
  - dir: downloader
  - dir: parser
  - dir: utils
- file: go.mod
- file: go.sum
- file: Makefile
- file: .goreleaser.yml
